//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Optic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Glasses
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Glasses()
        {
            this.Orders = new HashSet<Orders>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> IdGender { get; set; }
        public Nullable<int> IdBrand { get; set; }
        public Nullable<int> Articule { get; set; }
        public Nullable<int> IdTypeOfGlasses { get; set; }
        public Nullable<int> IdShapeOfGlasses { get; set; }
        public byte[] Image { get; set; }
        public Nullable<int> IdDiopterLeftEyes { get; set; }
        public Nullable<int> IdDiopterRightEyes { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual DiopterLeftEyes DiopterLeftEyes { get; set; }
        public virtual DiopterRightEyes DiopterRightEyes { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual ShapeOfGlasses ShapeOfGlasses { get; set; }
        public virtual TypeOfGlasses TypeOfGlasses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
    }
}
