//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Optic.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OpticEntities : DbContext
    {
        public OpticEntities()
            : base("name=OpticEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Brand> Brand { get; set; }
        public virtual DbSet<DiopterLeftEyes> DiopterLeftEyes { get; set; }
        public virtual DbSet<DiopterRightEyes> DiopterRightEyes { get; set; }
        public virtual DbSet<Gender> Gender { get; set; }
        public virtual DbSet<Glasses> Glasses { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<ShapeOfGlasses> ShapeOfGlasses { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TypeOfGlasses> TypeOfGlasses { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
